/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as AuthenticatedAppCfdRouteImport } from './routes/_authenticated/app.cfd'
import { Route as AuthenticatedAppMarketsRouteImport } from './routes/_authenticated/app.markets'
import { Route as AuthenticatedAppPortfolioRouteImport } from './routes/_authenticated/app.portfolio'
import { Route as AuthenticatedAppRoboRouteImport } from './routes/_authenticated/app.robo'
import { Route as AuthenticatedAppStockRouteImport } from './routes/_authenticated/app.stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/app/account',
  path: '/app/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCfdRoute = AuthenticatedAppCfdRouteImport.update({
  id: '/app/cfd',
  path: '/app/cfd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMarketsRoute = AuthenticatedAppMarketsRouteImport.update({
  id: '/app/markets',
  path: '/app/markets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPortfolioRoute =
  AuthenticatedAppPortfolioRouteImport.update({
    id: '/app/portfolio',
    path: '/app/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoboRoute = AuthenticatedAppRoboRouteImport.update({
  id: '/app/robo',
  path: '/app/robo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppStockRoute = AuthenticatedAppStockRouteImport.update({
  id: '/app/stock',
  path: '/app/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/cfd': typeof AuthenticatedAppCfdRoute
  '/app/markets': typeof AuthenticatedAppMarketsRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/robo': typeof AuthenticatedAppRoboRoute
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/cfd': typeof AuthenticatedAppCfdRoute
  '/app/markets': typeof AuthenticatedAppMarketsRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/robo': typeof AuthenticatedAppRoboRoute
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/cfd': typeof AuthenticatedAppCfdRoute
  '/_authenticated/app/markets': typeof AuthenticatedAppMarketsRoute
  '/_authenticated/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/_authenticated/app/robo': typeof AuthenticatedAppRoboRoute
  '/_authenticated/app/stock': typeof AuthenticatedAppStockRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/account'
    | '/app/cfd'
    | '/app/markets'
    | '/app/portfolio'
    | '/app/robo'
    | '/app/stock'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/account'
    | '/app/cfd'
    | '/app/markets'
    | '/app/portfolio'
    | '/app/robo'
    | '/app/stock'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/app/account'
    | '/_authenticated/app/cfd'
    | '/_authenticated/app/markets'
    | '/_authenticated/app/portfolio'
    | '/_authenticated/app/robo'
    | '/_authenticated/app/stock'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cfd': {
      id: '/_authenticated/app/cfd'
      path: '/app/cfd'
      fullPath: '/app/cfd'
      preLoaderRoute: typeof AuthenticatedAppCfdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/markets': {
      id: '/_authenticated/app/markets'
      path: '/app/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AuthenticatedAppMarketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/portfolio': {
      id: '/_authenticated/app/portfolio'
      path: '/app/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AuthenticatedAppPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/robo': {
      id: '/_authenticated/app/robo'
      path: '/app/robo'
      fullPath: '/app/robo'
      preLoaderRoute: typeof AuthenticatedAppRoboRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/stock': {
      id: '/_authenticated/app/stock'
      path: '/app/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AuthenticatedAppStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppCfdRoute: typeof AuthenticatedAppCfdRoute
  AuthenticatedAppMarketsRoute: typeof AuthenticatedAppMarketsRoute
  AuthenticatedAppPortfolioRoute: typeof AuthenticatedAppPortfolioRoute
  AuthenticatedAppRoboRoute: typeof AuthenticatedAppRoboRoute
  AuthenticatedAppStockRoute: typeof AuthenticatedAppStockRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppCfdRoute: AuthenticatedAppCfdRoute,
  AuthenticatedAppMarketsRoute: AuthenticatedAppMarketsRoute,
  AuthenticatedAppPortfolioRoute: AuthenticatedAppPortfolioRoute,
  AuthenticatedAppRoboRoute: AuthenticatedAppRoboRoute,
  AuthenticatedAppStockRoute: AuthenticatedAppStockRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
