/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as Public404RouteImport } from './routes/_public/404'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicBlogRouteImport } from './routes/_public/blog'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicDemoRouteImport } from './routes/_public/demo'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicFeaturesRouteImport } from './routes/_public/features'
import { Route as PublicImprintRouteImport } from './routes/_public/imprint'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicWaitlistRouteImport } from './routes/_public/waitlist'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as AuthenticatedAppCfdRouteImport } from './routes/_authenticated/app.cfd'
import { Route as AuthenticatedAppMarketsRouteImport } from './routes/_authenticated/app.markets'
import { Route as AuthenticatedAppPortfolioRouteImport } from './routes/_authenticated/app.portfolio'
import { Route as AuthenticatedAppRoboRouteImport } from './routes/_authenticated/app.robo'
import { Route as AuthenticatedAppStockRouteImport } from './routes/_authenticated/app.stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Public404Route = Public404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDemoRoute = PublicDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFeaturesRoute = PublicFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicImprintRoute = PublicImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicWaitlistRoute = PublicWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/app/account',
  path: '/app/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCfdRoute = AuthenticatedAppCfdRouteImport.update({
  id: '/app/cfd',
  path: '/app/cfd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMarketsRoute = AuthenticatedAppMarketsRouteImport.update({
  id: '/app/markets',
  path: '/app/markets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPortfolioRoute =
  AuthenticatedAppPortfolioRouteImport.update({
    id: '/app/portfolio',
    path: '/app/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoboRoute = AuthenticatedAppRoboRouteImport.update({
  id: '/app/robo',
  path: '/app/robo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppStockRoute = AuthenticatedAppStockRouteImport.update({
  id: '/app/stock',
  path: '/app/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/404': typeof Public404Route
  '/about': typeof PublicAboutRoute
  '/blog': typeof PublicBlogRoute
  '/contact': typeof PublicContactRoute
  '/demo': typeof PublicDemoRoute
  '/faq': typeof PublicFaqRoute
  '/features': typeof PublicFeaturesRoute
  '/imprint': typeof PublicImprintRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/waitlist': typeof PublicWaitlistRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/cfd': typeof AuthenticatedAppCfdRoute
  '/app/markets': typeof AuthenticatedAppMarketsRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/robo': typeof AuthenticatedAppRoboRoute
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/404': typeof Public404Route
  '/about': typeof PublicAboutRoute
  '/blog': typeof PublicBlogRoute
  '/contact': typeof PublicContactRoute
  '/demo': typeof PublicDemoRoute
  '/faq': typeof PublicFaqRoute
  '/features': typeof PublicFeaturesRoute
  '/imprint': typeof PublicImprintRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/waitlist': typeof PublicWaitlistRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/cfd': typeof AuthenticatedAppCfdRoute
  '/app/markets': typeof AuthenticatedAppMarketsRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/robo': typeof AuthenticatedAppRoboRoute
  '/app/stock': typeof AuthenticatedAppStockRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_public/404': typeof Public404Route
  '/_public/about': typeof PublicAboutRoute
  '/_public/blog': typeof PublicBlogRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/demo': typeof PublicDemoRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/features': typeof PublicFeaturesRoute
  '/_public/imprint': typeof PublicImprintRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/waitlist': typeof PublicWaitlistRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/cfd': typeof AuthenticatedAppCfdRoute
  '/_authenticated/app/markets': typeof AuthenticatedAppMarketsRoute
  '/_authenticated/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/_authenticated/app/robo': typeof AuthenticatedAppRoboRoute
  '/_authenticated/app/stock': typeof AuthenticatedAppStockRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/404'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/faq'
    | '/features'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/waitlist'
    | '/app/account'
    | '/app/cfd'
    | '/app/markets'
    | '/app/portfolio'
    | '/app/robo'
    | '/app/stock'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/404'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/faq'
    | '/features'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/waitlist'
    | '/app/account'
    | '/app/cfd'
    | '/app/markets'
    | '/app/portfolio'
    | '/app/robo'
    | '/app/stock'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/login'
    | '/signup'
    | '/_public/404'
    | '/_public/about'
    | '/_public/blog'
    | '/_public/contact'
    | '/_public/demo'
    | '/_public/faq'
    | '/_public/features'
    | '/_public/imprint'
    | '/_public/privacy'
    | '/_public/terms'
    | '/_public/waitlist'
    | '/_authenticated/app/account'
    | '/_authenticated/app/cfd'
    | '/_authenticated/app/markets'
    | '/_authenticated/app/portfolio'
    | '/_authenticated/app/robo'
    | '/_authenticated/app/stock'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/404': {
      id: '/_public/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Public404RouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/demo': {
      id: '/_public/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof PublicDemoRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/features': {
      id: '/_public/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof PublicFeaturesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/imprint': {
      id: '/_public/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof PublicImprintRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/waitlist': {
      id: '/_public/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof PublicWaitlistRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cfd': {
      id: '/_authenticated/app/cfd'
      path: '/app/cfd'
      fullPath: '/app/cfd'
      preLoaderRoute: typeof AuthenticatedAppCfdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/markets': {
      id: '/_authenticated/app/markets'
      path: '/app/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AuthenticatedAppMarketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/portfolio': {
      id: '/_authenticated/app/portfolio'
      path: '/app/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AuthenticatedAppPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/robo': {
      id: '/_authenticated/app/robo'
      path: '/app/robo'
      fullPath: '/app/robo'
      preLoaderRoute: typeof AuthenticatedAppRoboRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/stock': {
      id: '/_authenticated/app/stock'
      path: '/app/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AuthenticatedAppStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppCfdRoute: typeof AuthenticatedAppCfdRoute
  AuthenticatedAppMarketsRoute: typeof AuthenticatedAppMarketsRoute
  AuthenticatedAppPortfolioRoute: typeof AuthenticatedAppPortfolioRoute
  AuthenticatedAppRoboRoute: typeof AuthenticatedAppRoboRoute
  AuthenticatedAppStockRoute: typeof AuthenticatedAppStockRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppCfdRoute: AuthenticatedAppCfdRoute,
  AuthenticatedAppMarketsRoute: AuthenticatedAppMarketsRoute,
  AuthenticatedAppPortfolioRoute: AuthenticatedAppPortfolioRoute,
  AuthenticatedAppRoboRoute: AuthenticatedAppRoboRoute,
  AuthenticatedAppStockRoute: AuthenticatedAppStockRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  Public404Route: typeof Public404Route
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBlogRoute: typeof PublicBlogRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDemoRoute: typeof PublicDemoRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicFeaturesRoute: typeof PublicFeaturesRoute
  PublicImprintRoute: typeof PublicImprintRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicWaitlistRoute: typeof PublicWaitlistRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  Public404Route: Public404Route,
  PublicAboutRoute: PublicAboutRoute,
  PublicBlogRoute: PublicBlogRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDemoRoute: PublicDemoRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicFeaturesRoute: PublicFeaturesRoute,
  PublicImprintRoute: PublicImprintRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicWaitlistRoute: PublicWaitlistRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
